{% set version = "0.5.3" %}

package:
  name: nbgrader
  version: {{ version }}

source:
  url: https://github.com/jupyter/nbgrader/archive/v{{ version }}.tar.gz
  sha256: 0bea2b522fe23d0c68d3aaf434ffe59e52d88cf1f54791de5d4e4fab5e80467e

build:
  number: 0
  script: python -m pip install --no-deps .
  entry_points:
    - nbgrader = nbgrader.apps.nbgraderapp:main

requirements:
  build:
    - python
    - setuptools
    - pip
    - jupyter
  run:
    - python
    - setuptools
    - jupyter
    - jupyter_client
    - jupyter_core
    - nbformat
    - python-dateutil
    - requests
    - six
    - sqlalchemy
    - tornado
    - traitlets
    - jsonschema
    - alembic

test:
  requires:
    - nodejs
    - pytest
    - selenium
    - phantomjs
  source_files:
    - '*'
  imports:
    - nbgrader
  commands:
    - nbgrader -h
    - export USER=$(whoami)  # [not win]
    - py.test -v -x -m "not nbextensions"  # [not (win and py2k)]

about:
  home: https://github.com/jupyter/nbgrader
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.md
  summary: 'A system for assigning and grading Jupyter notebooks.'

extra:
  recipe-maintainers:
    - jhamrick
    - lgpage
