{% set version = "0.6.2" %}

package:
  name: nbgrader
  version: {{ version }}

source:
  url: https://github.com/jupyter/nbgrader/archive/v{{ version }}.tar.gz
  sha256: 09a6a79ea07867a844ab5b475e9784319dc441a5bd19ae71f8d853ae196b2180

build:
  number: 0
  # Cannot be noarch b/c of the post/pre scripts.
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - nbgrader = nbgrader.apps.nbgraderapp:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - sqlalchemy <1.4
    - python-dateutil
    - jupyter
    - notebook >=4.2
    - nbconvert =5.6.1
    - nbformat
    - traitlets =4.3.3
    - jupyter_core
    - jupyter_client
    - tornado
    - six >=1.11
    - requests
    - jsonschema
    - alembic
    - rapidfuzz

test:
  source_files:
    - '*'
  imports:
    - nbgrader
  commands:
    - nbgrader -h

about:
  home: https://github.com/jupyter/nbgrader
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A system for assigning and grading Jupyter notebooks

extra:
  recipe-maintainers:
    - jhamrick
    - lgpage
    - ocefpaf
    - BertR
