{% set gh_org = "jupyter" %}
{% set gh_repo = "nbgrader" %}
{% set version = "v0.5.0" %}
{% set sha256 = "759fb99278c345c0ee8548acee04e9859cd1436f03d3d0d35cfe53ca0d477286" %}

package:
  name: {{ gh_repo|lower }}
  version: {{ version }}

source:
  fn: {{ gh_repo }}-{{ version }}.tar.gz
  url: https://github.com/{{ gh_org }}/{{ gh_repo }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [win and py27]

requirements:
  build:
    - jupyter
    - jupyter_client
    - jupyter_core
    - nbconvert >=4.2
    - nbformat
    - notebook >=4.2
    - python
    - python-dateutil
    - requests
    - setuptools
    - six
    - sqlalchemy
    - tornado
    - traitlets
    - jsonschema
    - alembic

  run:
    - jupyter
    - jupyter_client
    - jupyter_core
    - nbconvert >=4.2
    - nbformat
    - notebook >=4.2
    - python
    - python-dateutil
    - requests
    - six
    - sqlalchemy
    - tornado
    - traitlets
    - jsonschema
    - alembic

test:
  requires:
    - nodejs
    - notebook >=4.2
    - pytest
    - python
    - requests
    - selenium
    - phantomjs

  source_files:
    - '*'

  imports:
    - nbgrader

about:
  home: https://github.com/{{ gh_org }}/{{ gh_repo }}
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.md
  summary: A system for assigning and grading Jupyter notebooks.

extra:
  recipe-maintainers:
    - jhamrick
    - lgpage
