{% set version = "v0.5.1" %}

package:
  name: nbgrader
  version: {{ version }}

source:
  url: https://github.com/jupyter/nbgrader/archive/{{ version }}.tar.gz
  sha256: 971a37b58a8f1a26e7b17eacb091879b5f1646f5097b717626436a266a178d33

build:
  number: 1
  script: python -m pip install --no-deps .
  entry_points:
    - nbgrader = nbgrader.apps.nbgraderapp:main

requirements:
  build:
    - python
    - setuptools
    - pip
    - jupyter
  run:
    - python
    - setuptools
    - jupyter
    - jupyter_client
    - jupyter_core
    - nbformat
    - python-dateutil
    - requests
    - six
    - sqlalchemy
    - tornado
    - traitlets
    - jsonschema
    - alembic

test:
  requires:
    - nodejs
    - pytest
    - selenium
    - phantomjs
  source_files:
    - '*'
  imports:
    - nbgrader
  commands:
    - nbgrader -h
    - export USER=$(whoami)  # [not win]
    - py.test -v -x -m "not nbextensions"

about:
  home: https://github.com/jupyter/nbgrader
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.md
  summary: 'A system for assigning and grading Jupyter notebooks.'

extra:
  recipe-maintainers:
    - jhamrick
    - lgpage
