{% set version = "0.7.1" %}

package:
  name: nbgrader
  version: {{ version }}

source:
  url: https://github.com/jupyter/nbgrader/archive/v{{ version }}.tar.gz
  sha256: da2ad6f08320d7a2b72a3d823f961cfbbc87dd925a0f9b9df6436617671e581e

build:
  number: 0
  # Cannot be noarch b/c of the post/pre scripts.
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - nbgrader = nbgrader.apps.nbgraderapp:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - sqlalchemy >=1.4,<2
    - python-dateutil >=2.8
    - notebook >=6.4,<7
    - nbconvert >=6
    - requests >=2.26
    - jsonschema >=3
    - alembic >=1.7
    - rapidfuzz >=1.8
    - Jinja2 >=3
    - MarkupSafe <2.2.0
    - jupyter_client <8
    - jupyter_server >=1.12
    - qtconsole >=5.2
    - ipywidgets >=7.6
    - nbclient >=0.6.1

test:
  imports:
    - nbgrader
  commands:
    - nbgrader -h

about:
  home: https://github.com/jupyter/nbgrader
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A system for assigning and grading Jupyter notebooks

extra:
  recipe-maintainers:
    - blink1073
    - jhamrick
    - lgpage
    - ocefpaf
    - BertR
    - SylvainCorlay
