{% set name = "nbgrader" %}
{% set version = "0.9.5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1ea898f3b1cd15ebd1f407591ac94b454244566876f0bc8740f5b1d501dc076a
  patches:
    # See https://github.com/jupyter/nbgrader/issues/1948
    - patches/0001-bump-jupyter-ydoc-dependency.patch

build:
  # caveat: no jupyterlab for py313 and 4.2.x
  skip: true # [py<38]
  number: 0
  script:
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - nbgrader = nbgrader.apps.nbgraderapp:main

requirements:
  build:
    - patch     # [not win]
    - msys2-patch  # [win]
  host:
    - pip
    - python
    - hatchling >=1.10.0
    - hatch-jupyter-builder >=0.7
  run:
    - python
    - alembic >=1.7
    - ipython >=8.10.0
    - ipywidgets >=7.6
    - jinja2 >=3
    - jsonschema >=3
    - jupyter_client <9
    - jupyter_server >=2
    # Officially jupyterlab>=4.2.0,<5 but to align with ydoc
    # dependency patch above
    - jupyterlab >=4.3.0,<5
    - jupyterlab_server
    - nbclient >=0.6.1
    - nbconvert >=6
    - notebook >=7.2.0,<8
    - python-dateutil >=2.8
    - rapidfuzz >=1.8
    - requests >=2.26
    - setuptools
    - sqlalchemy >=1.4,<3
    - pyyaml >=6.0

test:
  requires:
    - pip
    - msys2-grep  # [win]
  imports:
    - nbgrader
  commands:
    - pip check
    - nbgrader -h
    - jupyter lab --version
    - jupyter labextension list
    - jupyter server extension list
    - jupyter labextension list 1>labextensions 2>&1
    - jupyter server extension list 1>server_extensions 2>&1
    {% for ext in ["assignment_list", "course_list", "formgrader", "validate_assignment"] %}
    - grep -iE "nbgrader.server_extensions.{{ ext }}.*OK" server_extensions
    - grep -iE "nbgrader.server_extensions.{{ ext }}.*enabled" server_extensions
    {% endfor %}
    # The labextension output format changed in 4.2?
    #- grep -iE "nbgrader.*OK.*nbgrader" labextensions
    - grep -iE "nbgrader.*enabled.*OK" labextensions

about:
  home: https://github.com/jupyter/nbgrader
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
    - nbgrader/labextension/static/third-party-licenses.json
  summary: A system for assigning and grading Jupyter notebooks
  description: |
    nbgrader is a tool that facilitates creating and grading
    assignments in the Jupyter notebook. It allows instructors to
    easily create notebook-based assignments that include both coding
    exercises and written free-responses. nbgrader then also provides
    a streamlined interface for quickly grading completed assignments.
  doc_url: https://nbgrader.readthedocs.io
  dev_url: https://github.com/jupyter/nbgrader

extra:
  recipe-maintainers:
    - blink1073
    - jhamrick
    - lgpage
    - ocefpaf
    - BertR
    - SylvainCorlay
    - bollwyvl
  skip-lints:
    - python_build_tool_in_run
    - patch_must_be_in_build   # the linter knows about m2-patch
