travis:
  secure:
    BINSTAR_TOKEN: DsFQFqQmDeG4KxnOXsH3CJc1DWVSep3rAKqLXqfYrTE8QZ/O+QFKwQ/nr4wAKYj4hLVBR0Em6SoWPao065qLtyS/1s9Guy8zTAlnYSlCy3erFtXFi7f+WKoy9jETDNRw9ZVvJrl5cWjz48J/gKyvgKbhmJjZfi/UXaM+lvXnQQHKBcfWaE3/YwuwQDxb+nifTz3yGJkU3Tx3oWjldhkZBpm6GF1P2mOFCaPIa9+oOmL7CEGoSpBmz9iTblq+gWoNIdFRL7oLRrJoE9hucXSQrfPFGTrJMnOLV+IcLcAVa03KHGXdxInmzzk7VZOfB0D2C50JCbcyWP4OQWbU391OWVVhOeyq8iB7FqccfqgOXsigqiYw1xEfn7SN2IBGP+3AO4oMZ7jIPt4jD8ZCyT2IkF51NCMAn369tQFI87ncEONirCfj5Coke5fZgu2BnZ1AgBMfCT1LDxmy3v8WvXJ6ctj1iaRpxW49q3dqdyFyAD8NifOLXBsI8WjjY733My4uwcdwTLnljjLczoldr93GoB16/UmGT6+nZ6NCbZ0jCy6pjGfW1f/uAbZT36yqGbOZrMPEWWjIUTmNo0qc51NVGTxg5gg5r728ICeVcfR/At5GP2shNyWBOEl9xskTESEKIhKVd02PH0mvWM4q8fgcQp56dQguysGaWWzFuCs0u8s=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
