travis:
  secure:
    BINSTAR_TOKEN: Jojt8pXvhP836ZKKfz1yGMkenhEsTziOsbm0+c3JUvvwz98oDllCWFDR80eWsY7HnMAFKa25aBPt+hb5fJ4mLjPdEaS/GrASetqaVLHH9BOo9iPKN9RMhmmWgGbpZ8k7t35Mmlrq7ODvbfyJkjT2TnFahBbGirGHIUy/6m1ru+u0HLDCHxKsD7XFQ4Hpum6+b56lRBDOjOaVXS8XNlbaqx9DLDgaqsW1DI5oBNqJwNZJ2ilgh8KtNyhexGBvyMGM6DweutlEj4K+Zy4I7FOIHowXh0vSAcevi+ZdPrp9Q1jOS989vTOFpAcpc/86HWHRskuKGfpySUoBST/+mod2pxGmy7mO2zkXp0AiLRDFn/cxhikKX+rTXl/i6emGy0rvjBouom1sJgP/8fPkayrPTQ2eg6yzlrrF6ZsbheshjK+PBC6hVOnKIm6pYGibTaXB/icoHTohk0ciXKY/LFfa3J1dGdMGqU2dn9ZyP5aHI5+C5Z385rHXXL0UQjzx+kyBmX9RcjADl2Tsmjve2nBwe9IJthZE/Um97rfYnpzxfeHR2hesxdHiPiykr0hn5qkgY/2djevZiZmr9vC5oJ7hTHvvjHFTnt8puz4KSSFZ9hjfNJ4Jh8g3RIH4wPM9CrtJC0ZLPuzq7T+Pt47q7ZqhqIItSHMmgbQuiaWFnLAQOYc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
