travis:
  secure:
    BINSTAR_TOKEN: lCBb66kw8LmiA9ztQRwad9hPxdYATOVQTD4qFYTdPAZqtkTxBypfLlyt+EWOamEQN1SE3o5H/JBNK98WCl/7JIAxqf5HsnzUrHuDL+yPyG29AyDFMPFXf186GOLo2t2eH18Lg0m1DC7gMhznHyfwd8ntBn26mN3Phha71H2lIv6poGVsRNKdcJV1djoATHDvHkNLs+Of3dmwmICkUntpctbEH/qjJeqTKnTzXTk8ih1PNtjktjapXPE+pax6yA0hg/5qGpKesPyVpHZial5lGY+/jKLk/olft/Gdu/a8EM/8LooR+NaJSdLpivT6+3c2N/Xk90C+W6bkOPjCa/mj2axOXVFSbAONGKT/mt9ewcKXbJ8GRUk2YsOAjElneTbh1AJLRG7xLgEh8zCdHgg56ojML05OjIlcU9f7mkx9vepyBieZeMNqxJh6BOkaS9J0rbnv5RXLnIjqadOkQwKXnPg1E6iaOtPw5EaiRFCZm6qeyKl+PHVeF5GImJE9IX3rhR50f6mKUkj6p091iFHZFRzrKCYUyPoMu5aHTeg57h1nIvhj5JmsgPuMf/ACbL7L/74WlT0/KNnrHRXQPlOj2L76hyTkE/Fz3jXathxrQWMnZ/obISTgm8D4rEVg+51dwlV7y7LB/82CfkrSygPc7TYe9/6zZH5djBdg9ACPNvo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
